# Generated by Django 5.0.4 on 2024-08-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
