# Generated by Django 5.0.4 on 2024-08-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('vegetables', 'vegetables'), ('fruits', 'fruits'), ('groceryitems', 'groceryitems'), ('nonveg', 'nonveg')], max_length=50, unique=True),
        ),
    ]
