# Generated by Django 5.0.4 on 2024-07-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
